"""The server itself: what state it is in, and the operations that change that state.

Everything Discord-shaped lives elsewhere. This module is what you would want to have if
you were writing a CLI instead of a bot, and it is testable for the same reason.

Two rules from pzserver DESIGN section 10 are enforced here rather than in the commands,
so that no command can forget them:

*   **Nothing is cached.** `probe()` always issues a live `DescribeInstances` and, if the
    box is up, a live RCON call. The game server can be stopped from four places --
    Discord, the console, the idle watchdog, a budget alarm -- and three of them will
    never tell this process about it.
*   **Running is not ready.** `Stage.BOOTING` exists precisely so that "the instance is
    up" cannot be mistaken for "you can connect". PZ opens its ports minutes before the
    world has finished loading.
"""

from __future__ import annotations

import asyncio
import base64
import datetime as dt
import enum
import inspect
import json
import logging
import re
import shlex
from collections.abc import Awaitable, Callable
from dataclasses import dataclass

from . import rcon as rcon_mod
from . import sandbox
from .aws import Aws, CommandResult, Instance
from .config import Config
from .rcon import Rcon, RconAuthError, RconUnreachable

log = logging.getLogger(__name__)

# Read once: this is the module in this repo, shipped to the game server verbatim so the
# code that edits the world's rules is the code the tests here exercise.
_SANDBOX_SOURCE = inspect.getsource(sandbox)

Progress = Callable[[str], Awaitable[None]]

# Backup names are generated by pz-backup.sh as
#   2026-08-22T19-24-30Z__scheduled__optional-label.tar.zst
# Anything that does not match this is not something the bot will pass to a shell.
BACKUP_NAME = re.compile(
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z__"
    r"(scheduled|prestop|prerestore|manual)(__[A-Za-z0-9_-]{1,40})?"
    r"\.tar\.zst$"
)
LABEL = re.compile(r"^[A-Za-z0-9_-]{1,40}$")


class Stage(enum.StrEnum):
    STOPPED = "stopped"
    PENDING = "pending"  # EC2 is starting; the world has not begun loading
    BOOTING = "booting"  # EC2 up, RCON silent -- PZ is loading the world
    READY = "ready"  # RCON answers `players`. The only state that means "connect now"
    STOPPING = "stopping"
    UNKNOWN = "unknown"

    @property
    def emoji(self) -> str:
        return {
            Stage.STOPPED: "\N{MEDIUM BLACK CIRCLE}",
            Stage.PENDING: "\N{LARGE YELLOW CIRCLE}",
            Stage.BOOTING: "\N{LARGE ORANGE CIRCLE}",
            Stage.READY: "\N{LARGE GREEN CIRCLE}",
            Stage.STOPPING: "\N{LARGE ORANGE CIRCLE}",
            Stage.UNKNOWN: "\N{BLACK QUESTION MARK ORNAMENT}",
        }[self]


class OperationError(RuntimeError):
    """A command could not do what was asked. The message is shown to the user."""


@dataclass
class Snapshot:
    instance: Instance
    stage: Stage
    players: list[str]
    player_count: int
    rcon_error: str = ""

    @property
    def uptime(self) -> dt.timedelta | None:
        if not self.instance.launch_time or not self.instance.is_running:
            return None
        return dt.datetime.now(dt.UTC) - self.instance.launch_time


def _stage_for(instance: Instance, ready: bool) -> Stage:
    match instance.state:
        case "stopped":
            return Stage.STOPPED
        case "pending":
            return Stage.PENDING
        case "stopping" | "shutting-down":
            return Stage.STOPPING
        case "running":
            return Stage.READY if ready else Stage.BOOTING
        case _:
            return Stage.UNKNOWN


class GameServer:
    def __init__(self, aws: Aws, cfg: Config) -> None:
        self.aws = aws
        self.cfg = cfg
        self.rcon = Rcon(cfg.rcon_host, cfg.rcon_port, cfg.rcon_password)

    # --- Observation -----------------------------------------------------------------

    async def probe(self, *, rcon_timeout: float = 6.0) -> Snapshot:
        """Live state. Never cached, never inferred from a previous call."""
        instance = await self.aws.describe(self.cfg.game_instance_id)
        if not instance.is_running:
            return Snapshot(instance, _stage_for(instance, False), [], 0)

        # The private IP survives stop/start, but not a rebuild. Following it here means
        # a replaced instance does not need a bot restart.
        if instance.private_ip and instance.private_ip != self.rcon.host:
            log.info("game server private ip moved to %s", instance.private_ip)
            self.rcon.host = instance.private_ip

        try:
            out = await self.rcon.execute("players", timeout=rcon_timeout)
        except RconAuthError as exc:
            # Not a readiness problem: the server may be perfectly healthy and the bot's
            # copy of the password stale. Saying "still loading" here would hide it.
            return Snapshot(instance, Stage.UNKNOWN, [], 0, rcon_error=str(exc))
        except RconUnreachable as exc:
            return Snapshot(instance, Stage.BOOTING, [], 0, rcon_error=str(exc))

        if not rcon_mod.looks_ready(out):
            return Snapshot(
                instance,
                Stage.BOOTING,
                [],
                0,
                rcon_error="RCON answered but the response was not a player list",
            )
        return Snapshot(
            instance,
            Stage.READY,
            rcon_mod.parse_players(out),
            rcon_mod.parse_player_count(out),
        )

    # --- Lifecycle -------------------------------------------------------------------

    async def start(self, progress: Progress) -> Snapshot:
        """Stopped -> Pending -> Booting -> Ready, or clean up and raise.

        The failure path matters as much as the success path: a start that dies halfway
        leaves an m7i.xlarge running at $0.20/hour with no world on it, and nobody
        watching. Every exit from here either reaches Ready or stops the instance.
        """
        snap = await self.probe()
        if snap.stage is Stage.READY:
            return snap
        if snap.stage is Stage.STOPPING:
            raise OperationError(
                "The server is in the middle of shutting down. Wait for it to finish "
                "(about a minute) and start it again -- starting now would race the save."
            )
        if snap.stage in (Stage.PENDING, Stage.BOOTING):
            await progress("Already starting \N{EM DASH} following the one already in flight.")
        else:
            await progress("Starting the instance\N{HORIZONTAL ELLIPSIS}")
            await self.aws.start_instance(self.cfg.game_instance_id)

        started = asyncio.get_running_loop().time()

        def elapsed() -> int:
            return int(asyncio.get_running_loop().time() - started)

        # Phase 1: EC2 reports running.
        while True:
            snap = await self.probe()
            if snap.instance.is_running:
                break
            if elapsed() > self.cfg.start_running_timeout:
                await self._abort_start("the instance never reached `running`")
                raise OperationError(
                    f"The instance was still `{snap.instance.state}` after "
                    f"{self.cfg.start_running_timeout // 60} minutes. It has been stopped so "
                    "it cannot bill for nothing. This is an AWS-side problem \N{EM DASH} "
                    "try again."
                )
            await progress(f"Starting the instance\N{HORIZONTAL ELLIPSIS} ({elapsed()}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

        await progress(
            "Instance is up. Loading the world \N{EM DASH} this takes 2\N{EN DASH}5 minutes."
        )

        # Phase 2: RCON answers. This is the only definition of ready.
        while True:
            snap = await self.probe()
            if snap.stage is Stage.READY:
                return snap
            if snap.stage is Stage.UNKNOWN and snap.rcon_error:
                await self._abort_start("RCON rejected the bot's password")
                raise OperationError(
                    f"The world loaded but RCON refused the bot's password: "
                    f"{snap.rcon_error}\nThe instance has been stopped. Check "
                    f"`{self.cfg.ssm('rcon_password')}` against the server's .ini."
                )
            if elapsed() > self.cfg.start_ready_timeout:
                await self._abort_start("the world never finished loading")
                raise OperationError(
                    f"The instance came up but PZ never answered RCON within "
                    f"{self.cfg.start_ready_timeout // 60} minutes. It has been stopped. "
                    f"Check `journalctl -u pzserver` on {self.cfg.game_instance_id}."
                )
            mins, secs = divmod(elapsed(), 60)
            await progress(f"Loading the world\N{HORIZONTAL ELLIPSIS} ({mins}m {secs:02d}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

    async def _abort_start(self, why: str) -> None:
        log.error("aborting start: %s", why)
        try:
            await self.aws.stop_instance(self.cfg.game_instance_id)
        except Exception:  # noqa: BLE001 -- the caller is already raising; log and move on
            log.exception("could not stop the instance after a failed start")

    async def stop(self, progress: Progress, *, force: bool = False) -> None:
        """Warn, save, back up, stop.

        The save is not this function's responsibility to guarantee -- pzserver.service's
        ExecStop runs `pz-rcon save` on the way down no matter who initiated the stop
        (pzserver DESIGN G5), and the instance's shutdown behaviour is ACPI stop, so
        `ec2:StopInstances` reaches it. What this adds is the human part: telling players
        first, and taking a `prestop` archive to S3 while the world is still up.
        """
        snap = await self.probe()
        if snap.instance.is_stopped:
            raise OperationError("The server is already stopped.")
        if snap.stage is Stage.STOPPING:
            raise OperationError("The server is already shutting down.")

        grace = 0 if force or snap.player_count == 0 else self.cfg.stop_grace_seconds
        if grace:
            await progress(
                f"{snap.player_count} player(s) online \N{EM DASH} warning them and waiting "
                f"{grace}s before shutting down."
            )
            await self._broadcast(f"Server shutting down in {grace} seconds. Get somewhere safe.")
            # Warn again near the end; a message ninety seconds ago is not a warning.
            await asyncio.sleep(max(grace - 30, 0))
            await self._broadcast("Server shutting down in 30 seconds.")
            await asyncio.sleep(min(grace, 30))

        await progress("Saving and backing up\N{HORIZONTAL ELLIPSIS}")
        result = await self.aws.run_shell(
            self.cfg.game_instance_id,
            ["/opt/pz/bin/pz-backup.sh prestop pzbot"],
            timeout=900,
            comment="pzbot /pz stop",
        )
        if not result.ok:
            # Deliberately not fatal. The backup is the *second* line of defence; the
            # first is ExecStop, which runs regardless. Refusing to stop here would mean
            # a broken backup script keeps an expensive instance running indefinitely.
            log.error("pre-stop backup failed: %s", result.output[-2000:])
            await progress(
                "\N{WARNING SIGN} The pre-stop backup failed \N{EM DASH} stopping anyway. "
                "The world is still saved on the way down by `ExecStop`, but check the "
                "backup script."
            )

        await progress("Stopping the instance\N{HORIZONTAL ELLIPSIS}")
        await self.aws.stop_instance(self.cfg.game_instance_id)

        deadline = asyncio.get_running_loop().time() + 300
        while asyncio.get_running_loop().time() < deadline:
            await asyncio.sleep(self.cfg.poll_seconds)
            instance = await self.aws.describe(self.cfg.game_instance_id)
            if instance.is_stopped:
                return
            await progress(f"Stopping the instance\N{HORIZONTAL ELLIPSIS} (`{instance.state}`)")
        raise OperationError(
            "`ec2:StopInstances` was accepted but the instance is still not `stopped` "
            "after 5 minutes. It may still be saving a large world. Check `/pz status`; "
            "if it is still running in ten minutes, stop it from the console."
        )

    async def restart(self, progress: Progress) -> Snapshot:
        """Bounce PZ without stopping the instance.

        `systemctl restart` runs ExecStop, which saves and quits, so this inherits the
        same guarantee a full stop has.
        """
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError("The instance is not running \N{EM DASH} use `/pz start` instead.")

        if snap.player_count:
            await self._broadcast("Server restarting in 30 seconds. Get somewhere safe.")
            await progress(
                f"Warning {snap.player_count} player(s), restarting in 30s\N{HORIZONTAL ELLIPSIS}"
            )
            await asyncio.sleep(30)

        await progress("Restarting the server (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
        result = await self.aws.run_shell(
            self.cfg.game_instance_id,
            ["systemctl restart pzserver.service"],
            timeout=300,
            comment="pzbot /pz restart",
        )
        if not result.ok:
            raise OperationError(f"`systemctl restart` failed:\n```\n{result.output[-1500:]}\n```")

        return await self._wait_until_ready(
            progress,
            timeout=self.cfg.start_ready_timeout,
            timeout_message=(
                "The server restarted but never answered RCON again. The instance has "
                "been left running deliberately so the logs survive \N{EM DASH} check "
                "`journalctl -u pzserver`, then `/pz stop` when you are done."
            ),
        )

    async def _wait_until_ready(
        self, progress: Progress, *, timeout: int, timeout_message: str
    ) -> Snapshot:
        """Poll until RCON answers, or give up with the caller's own explanation.

        Deliberately does not stop the instance on timeout: every caller of this is a
        server that was already running and is expected to still be running afterwards.
        `start()` has its own loop precisely because its failure path is the opposite --
        there, a box that never became ready must be stopped so it cannot bill.
        """
        started = asyncio.get_running_loop().time()
        while True:
            elapsed = int(asyncio.get_running_loop().time() - started)
            snap = await self.probe()
            if snap.stage is Stage.READY:
                return snap
            if elapsed > timeout:
                raise OperationError(timeout_message)
            mins, secs = divmod(elapsed, 60)
            await progress(f"Loading the world\N{HORIZONTAL ELLIPSIS} ({mins}m {secs:02d}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

    # --- RCON-level operations -------------------------------------------------------

    async def save(self) -> str:
        snap = await self.probe()
        if snap.stage is not Stage.READY:
            raise OperationError(
                f"The server is `{snap.stage}` \N{EM DASH} there is nothing to save yet."
            )
        return await self.rcon.execute("save", timeout=30)

    async def _broadcast(self, message: str) -> None:
        # Quoted, because PZ's servermsg takes a single quoted argument. Callers pass
        # literals; nothing here is user-supplied.
        try:
            await self.rcon.execute(f'servermsg "{message}"')
        except rcon_mod.RconError as exc:
            log.warning("could not broadcast %r: %s", message, exc)

    # --- Backups ---------------------------------------------------------------------

    async def backup_now(self, label: str = "") -> CommandResult:
        if label and not LABEL.fullmatch(label):
            raise OperationError(
                "A backup label may only contain letters, numbers, `-` and `_` "
                "(40 characters max). It ends up in a filename and an S3 key."
            )
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                "The instance is stopped \N{EM DASH} there is nothing to back up live."
            )

        argv = ["/opt/pz/bin/pz-backup.sh", "manual"]
        if label:
            argv.append(shlex.quote(label))
        return await self.aws.run_shell(
            self.cfg.game_instance_id,
            [" ".join(argv)],
            timeout=1800,
            comment="pzbot /pz backup now",
        )

    async def restore(self, backup_name: str, progress: Progress) -> CommandResult:
        """Stop PZ, restore, bring it back. The most dangerous thing the bot can do.

        `pz-restore.sh` carries the real guards -- it refuses to run under a live server,
        takes a `prerestore` backup first, and refuses a partial archive. What is added
        here is that the name is checked against the actual S3 listing before it goes
        anywhere near a shell.
        """
        if not BACKUP_NAME.fullmatch(backup_name):
            raise OperationError(f"`{backup_name}` is not a backup name produced by this stack.")

        backups = await self.aws.list_backups(self.cfg.backup_bucket, self.cfg.stack)
        if backup_name not in {b.name for b in backups}:
            raise OperationError(
                f"No backup named `{backup_name}` in "
                f"`s3://{self.cfg.backup_bucket}/backups/{self.cfg.stack}/`. "
                "Use `/pz backup list` to see what exists."
            )

        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                "The instance must be running to restore. `/pz start` first \N{EM DASH} the "
                "restore stops the game itself, but it needs the box up to do the work."
            )
        if snap.player_count:
            raise OperationError(
                f"{snap.player_count} player(s) are online. Restoring would delete the "
                "session they are in. Get everyone off first."
            )

        await progress("Stopping the game (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
        stop = await self.aws.run_shell(
            self.cfg.game_instance_id,
            ["systemctl stop pzserver.service"],
            timeout=300,
            comment="pzbot /pz restore (stop)",
        )
        if not stop.ok:
            raise OperationError(
                "Could not stop the game, so nothing was restored:\n"
                f"```\n{stop.output[-1200:]}\n```"
            )

        await progress(
            "Taking a prerestore backup and restoring\N{HORIZONTAL ELLIPSIS} "
            "(this can take a while)"
        )
        result = await self.aws.run_shell(
            self.cfg.game_instance_id,
            [f"/opt/pz/bin/pz-restore.sh {shlex.quote(backup_name)} --yes"],
            timeout=3600,
            comment="pzbot /pz restore",
        )
        if not result.ok:
            raise OperationError(
                "The restore failed. `pz-restore.sh` fails closed \N{EM DASH} your world has "
                "not been touched, and the prerestore backup it took is intact. The game is "
                "still stopped; `/pz restart` brings it back on the old world.\n"
                f"```\n{result.output[-1200:]}\n```"
            )

        await progress("Restored. Starting the game back up\N{HORIZONTAL ELLIPSIS}")
        start = await self.aws.run_shell(
            self.cfg.game_instance_id,
            ["systemctl start pzserver.service"],
            timeout=300,
            comment="pzbot /pz restore (start)",
        )
        if not start.ok:
            raise OperationError(
                "The restore succeeded but the server did not come back up:\n"
                f"```\n{start.output[-1200:]}\n```"
            )
        return result

    # --- Running our own code on the game server -------------------------------------

    async def _require_instance_running(self, what: str) -> Snapshot:
        """SSM only reaches a running instance, and "InvalidInstanceId" explains nothing.

        Every path that runs something on the game server goes through here, so the
        answer to "why did /pz config get just throw an AWS error" is a sentence about
        the server being off instead.
        """
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                f"The instance is stopped, so {what} is not reachable \N{EM DASH} the data "
                "volume it lives on is only attached while the box is up. `/pz start` first."
            )
        return snap

    async def run_python(
        self, source: str, args: list[str], *, comment: str, timeout: int = 120
    ) -> CommandResult:
        """Run a Python module of ours on the game server, over SSM.

        The module is base64-encoded on the way, which is not obfuscation -- it is the
        only way to put a multi-line program through a shell command string without
        every quote and dollar sign in it becoming a bug. Arguments still go through
        `shlex.quote`, and they have already been validated by an allowlist before they
        get here.

        The point of this over embedding a script inline: the code that runs on the box
        is byte-for-byte the module that is unit-tested in this repo, instead of a second
        implementation living in a string.
        """
        payload = base64.b64encode(source.encode("utf-8")).decode("ascii")
        argv = " ".join(shlex.quote(arg) for arg in args)
        return await self.aws.run_shell(
            self.cfg.game_instance_id,
            [f"echo {payload} | base64 -d | python3 - {argv}"],
            timeout=timeout,
            comment=comment,
        )

    # --- Sandbox options (the world's rules) -----------------------------------------

    @property
    def sandbox_path(self) -> str:
        return f"/opt/pz/data/Zomboid/Server/{self.cfg.server_name}_SandboxVars.lua"

    async def sandbox_read(self) -> dict[str, str]:
        """Every sandbox value the world currently has, as raw Lua literals."""
        await self._require_instance_running("the world's settings file")
        result = await self.run_python(
            _SANDBOX_SOURCE,
            ["get", self.sandbox_path],
            comment="pzbot /pz sandbox get",
        )
        if not result.ok:
            raise OperationError(
                f"Could not read the sandbox options:\n```\n{result.output[-800:]}\n```"
            )
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise OperationError(f"Unreadable response from the game server: {exc}") from None

    async def sandbox_set(
        self, path: str, value: str, progress: Progress, *, apply: bool = True
    ) -> dict[str, str]:
        """Change one sandbox option.

        Unlike the .ini, this file is only read when the server starts, so there is no
        `reloadoptions` equivalent -- the change lands on the next boot or not at all.
        Worse, a running server owns the file: an admin changing an option from inside
        the game rewrites it wholesale, which would silently undo an edit made
        underneath. So when `apply` is set and the game is up, the order is
        **stop, edit, start** rather than edit-then-restart. There is no window in which
        both this bot and the game think they own the file.
        """
        try:
            literal = sandbox.coerce(path, value)
        except sandbox.SandboxError as exc:
            raise OperationError(str(exc)) from None

        snap = await self._require_instance_running("the world's settings file")

        game_was_up = snap.stage in (Stage.READY, Stage.BOOTING)
        if apply and game_was_up:
            if snap.player_count:
                await self._broadcast(
                    "Server restarting in 30 seconds to change the world settings."
                )
                await progress(
                    f"Warning {snap.player_count} player(s), restarting in 30s"
                    "\N{HORIZONTAL ELLIPSIS}"
                )
                await asyncio.sleep(30)
            await progress("Stopping the game (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
            stop = await self.aws.run_shell(
                self.cfg.game_instance_id,
                ["systemctl stop pzserver.service"],
                timeout=300,
                comment="pzbot /pz sandbox set (stop)",
            )
            if not stop.ok:
                raise OperationError(
                    "Could not stop the game, so nothing was changed:\n"
                    f"```\n{stop.output[-1000:]}\n```"
                )

        result = await self.run_python(
            _SANDBOX_SOURCE,
            ["set", self.sandbox_path, path, literal],
            comment="pzbot /pz sandbox set",
        )
        if not result.ok:
            if apply and game_was_up:
                # The edit failed with the game already stopped. Put it back up on the
                # old settings rather than leaving an instance running with no server on
                # it -- that is the state that bills without anyone able to play.
                await progress(
                    "The edit failed. Starting the server back up unchanged\N{HORIZONTAL ELLIPSIS}"
                )
                await self.aws.run_shell(
                    self.cfg.game_instance_id,
                    ["systemctl start pzserver.service"],
                    timeout=300,
                    comment="pzbot /pz sandbox set (recover)",
                )
            raise OperationError(
                f"Could not change the sandbox options:\n```\n{result.output[-800:]}\n```"
            )

        try:
            changed = json.loads(result.stdout)
        except json.JSONDecodeError:
            changed = {"setting": path, "was": "?", "now": literal}

        if apply and game_was_up:
            await progress("Starting back up on the new settings\N{HORIZONTAL ELLIPSIS}")
            start = await self.aws.run_shell(
                self.cfg.game_instance_id,
                ["systemctl start pzserver.service"],
                timeout=300,
                comment="pzbot /pz sandbox set (start)",
            )
            if not start.ok:
                raise OperationError(
                    "The setting was changed, but the server did not come back up. The "
                    "previous file is on the box as `*_SandboxVars.lua.pzbot.bak`.\n"
                    f"```\n{start.output[-1000:]}\n```"
                )
            await self._wait_until_ready(
                progress,
                timeout=self.cfg.start_ready_timeout,
                timeout_message=(
                    "The setting was changed and the server was restarted, but it never "
                    "answered RCON again. The instance has been left running so the logs "
                    "survive -- check `journalctl -u pzserver`. The previous file is on "
                    "the box as `*_SandboxVars.lua.pzbot.bak`."
                ),
            )

        changed["applied"] = "yes" if (apply and game_was_up) else "next start"
        return changed

    # --- The .ini allowlist ----------------------------------------------------------

    @property
    def ini_path(self) -> str:
        return f"/opt/pz/data/Zomboid/Server/{self.cfg.server_name}.ini"

    async def ini_read(self) -> dict[str, str]:
        await self._require_instance_running("the server's .ini")
        keys = "|".join(INI_KEYS)
        result = await self.aws.run_shell(
            self.cfg.game_instance_id,
            [f"grep -E '^({keys})=' {shlex.quote(self.ini_path)} || true"],
            timeout=60,
            comment="pzbot /pz config get",
        )
        if not result.ok:
            raise OperationError(f"Could not read the .ini:\n```\n{result.output[-800:]}\n```")
        values: dict[str, str] = {}
        for line in result.stdout.splitlines():
            if "=" in line:
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
        return values

    async def ini_write(self, key: str, value: str) -> str:
        """Set one allowlisted key, then make PZ re-read the file.

        The allowlist is the whole security model here. `/pz config` must not become a
        way to edit an arbitrary line of an arbitrary file on the game server from a chat
        message -- so the key is looked up in a table (never interpolated from input),
        and the value is validated by that table's own rule before it goes anywhere.
        """
        spec = INI_KEYS.get(key)
        if spec is None:
            raise OperationError(f"`{key}` is not an editable key. See `/pz config get`.")
        value = spec.clean(value)

        snap = await self._require_instance_running("the server's .ini")

        # Shipped and run the same way as the sandbox editor, rather than embedded in a
        # shell string: the key and the value arrive as argv, so no amount of quoting in
        # either can become shell syntax.
        result = await self.run_python(
            _INI_SCRIPT,
            [self.ini_path, key, value],
            comment="pzbot /pz config set",
        )
        if not result.ok:
            raise OperationError(f"Could not write the .ini:\n```\n{result.output[-800:]}\n```")

        if snap.stage is Stage.READY:
            try:
                await self.rcon.execute("reloadoptions", timeout=30)
            except rcon_mod.RconError as exc:
                return (
                    f"`{key}` is now `{value}` in the .ini, but `reloadoptions` failed "
                    f"({exc}). It will take effect on the next restart."
                )
            return f"`{key}` is now `{value}`, and the server has reloaded its options."
        return f"`{key}` is now `{value}`. It takes effect on the next start."

    # --- Idle shutdown ---------------------------------------------------------------

    async def set_idle(self, timeout_min: int, warn_min: int) -> str:
        """Retune the watchdog for the current session.

        This edits `/etc/pz/env` on the game server rather than Parameter Store, and that
        is not a shortcut -- it is the only door the bot has. `pz-bot-role` deliberately
        has no `ssm:PutParameter` (pzserver DESIGN section 9), and `pz-config.service`
        re-renders that file from Parameter Store on every boot, so a change made here
        lasts exactly as long as the session it was made in. Making it permanent means
        `prod.tfvars` and an apply, which is a decision worth taking outside of chat.
        """
        if not 5 <= timeout_min <= 1440:
            raise OperationError("The idle timeout must be between 5 and 1440 minutes.")
        warn_min = max(1, min(warn_min, timeout_min - 1))

        result = await self.aws.run_shell(
            self.cfg.game_instance_id,
            [
                "set -e",
                f"sed -i -E 's/^PZ_IDLE_TIMEOUT_MIN=.*/PZ_IDLE_TIMEOUT_MIN={timeout_min}/' "
                "/etc/pz/env",
                f"sed -i -E 's/^PZ_IDLE_WARN_MIN=.*/PZ_IDLE_WARN_MIN={warn_min}/' /etc/pz/env",
                # Clear the "already warned" flag so the new threshold gets its own warning.
                "rm -f /var/lib/pz/idle-warned /var/lib/pz/idle-minutes",
                "grep -E '^PZ_IDLE' /etc/pz/env",
            ],
            timeout=60,
            comment="pzbot /pz idle",
        )
        if not result.ok:
            raise OperationError(
                f"Could not retune the watchdog:\n```\n{result.output[-800:]}\n```"
            )
        return result.stdout.strip()


# Run on the game server by `ini_write`. Plain argv in, one line changed, nothing else
# touched -- the same contract as the sandbox editor, for the same reason.
_INI_SCRIPT = """
import sys

path, key, value = sys.argv[1], sys.argv[2], sys.argv[3]
lines = open(path, encoding="utf-8").read().splitlines()

out, found = [], False
for line in lines:
    if line.split("=", 1)[0].strip() == key:
        out.append(key + "=" + value)
        found = True
    else:
        out.append(line)
if not found:
    out.append(key + "=" + value)

open(path, "w", encoding="utf-8").write("\\n".join(out) + "\\n")
print(("updated " if found else "added ") + key)
"""


@dataclass(frozen=True)
class IniKey:
    """One editable server option, and the rule that keeps it editable-but-safe."""

    kind: str  # int | bool | text
    help: str
    low: int = 0
    high: int = 0
    max_len: int = 200

    def clean(self, value: str) -> str:
        value = value.strip()
        if self.kind == "int":
            try:
                number = int(value)
            except ValueError:
                raise OperationError(f"`{value}` is not a number.") from None
            if not self.low <= number <= self.high:
                raise OperationError(f"Must be between {self.low} and {self.high}.")
            return str(number)
        if self.kind == "bool":
            if value.lower() in ("true", "yes", "on", "1"):
                return "true"
            if value.lower() in ("false", "no", "off", "0"):
                return "false"
            raise OperationError(f"`{value}` is not true or false.")
        # Text. Newlines would inject a second .ini line, and `=` would split the key.
        if len(value) > self.max_len:
            raise OperationError(f"Too long — {self.max_len} characters max.")
        if re.search(r"[\x00-\x1f]", value) or "=" in value:
            raise OperationError(
                "No control characters and no `=` \N{EM DASH} both corrupt the .ini."
            )
        return value


# Deliberately short. Every entry here is something a group actually changes mid-season;
# anything structural (ports, passwords, the world name) belongs in Terraform, where it
# is reviewed, and not in a chat message.
INI_KEYS: dict[str, IniKey] = {
    "PublicName": IniKey("text", "Name shown in the server browser", max_len=64),
    "PublicDescription": IniKey("text", "Description shown in the server browser"),
    "ServerWelcomeMessage": IniKey("text", "Message shown to a player on connect", max_len=300),
    "MaxPlayers": IniKey("int", "Player slots", low=1, high=64),
    "PauseEmpty": IniKey("bool", "Pause the world when nobody is online"),
    "GlobalChat": IniKey("bool", "Server-wide chat channel"),
    "PVP": IniKey("bool", "Player versus player damage"),
    "SafetySystem": IniKey("bool", "PVP safety toggle system"),
    "SleepAllowed": IniKey("bool", "Let players sleep"),
    "DisplayUserName": IniKey("bool", "Show usernames above characters"),
    "NoFire": IniKey("bool", "Disable fire spread"),
    "AnnounceDeath": IniKey("bool", "Announce deaths in chat"),
}
