"""The server itself: what state it is in, and the operations that change that state.

Everything Discord-shaped lives elsewhere. This module is what you would want to have if
you were writing a CLI instead of a bot, and it is testable for the same reason.

Two rules from pzserver DESIGN section 10 are enforced here rather than in the commands,
so that no command can forget them:

*   **Nothing is cached.** `probe()` always issues a live `DescribeInstances` and, if the
    box is up, a live RCON call. The game server can be stopped from four places --
    Discord, the console, the idle watchdog, a budget alarm -- and three of them will
    never tell this process about it.
*   **Running is not ready.** `Stage.BOOTING` exists precisely so that "the instance is
    up" cannot be mistaken for "you can connect". PZ opens its ports minutes before the
    world has finished loading.
"""

from __future__ import annotations

import asyncio
import datetime as dt
import enum
import json
import logging
import re
from collections.abc import Awaitable, Callable
from dataclasses import dataclass

from . import rcon as rcon_mod
from . import sandbox
from .aws import Aws, AwsError, Backup, CommandResult, Instance, is_instance_gone
from .config import Config
from .rcon import Rcon, RconAuthError, RconUnreachable

log = logging.getLogger(__name__)

Progress = Callable[[str], Awaitable[None]]

# Backup names are generated by pz-backup.sh as
#   2026-08-22T19-24-30Z__scheduled__optional-label.tar.zst
# Anything that does not match this is not something the bot will pass to a shell.
BACKUP_NAME = re.compile(
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z__"
    r"(scheduled|prestop|prerestore|manual)(__[A-Za-z0-9_-]{1,40})?"
    r"\.tar\.zst$"
)
LABEL = re.compile(r"^[A-Za-z0-9_-]{1,40}$")

# How long a `/pz backup download` link is signed for, in minutes. The ceiling is short
# on purpose: the link is a bearer credential for an archive containing `db/`, which is
# where player accounts live, and it cannot be revoked once handed out. Fifteen minutes
# is plenty to *start* a download -- S3 checks the signature when the request opens, not
# while the bytes are flowing, so a 2 GB archive on a slow line is unaffected.
DOWNLOAD_TTL_DEFAULT = 15
DOWNLOAD_TTL_MIN = 5
DOWNLOAD_TTL_MAX = 60

# Mirror pzserver's `pz-<stack>-version` and `pz-<stack>-mods` document patterns. Same
# rule as BACKUP_NAME above: the document is the enforcement, this is the error message.
STEAM_BRANCH = re.compile(r"^[A-Za-z0-9._-]{1,32}$")
WORKSHOP_ID = re.compile(r"^[0-9]{1,12}$")
MOD_ID = re.compile(r"^[A-Za-z0-9_.-]{1,64}$")

# Offered in the picker, not enforced: Steam publishes whatever branches it likes and PZ
# has renamed these before, so a branch name that is not here is typed rather than
# refused. SteamCMD's own error for a branch that does not exist is clear enough.
STEAM_BRANCHES: dict[str, str] = {
    "public": "The default branch \N{EM DASH} the current stable build",
    "unstable": "The public beta, where new builds land first",
    "b41multiplayer": "Build 41 multiplayer, for a world that cannot move to 42",
}


class Stage(enum.StrEnum):
    STOPPED = "stopped"
    PENDING = "pending"  # EC2 is starting; the world has not begun loading
    BOOTING = "booting"  # EC2 up, RCON silent -- PZ is loading the world
    READY = "ready"  # RCON answers `players`. The only state that means "connect now"
    STOPPING = "stopping"
    UNKNOWN = "unknown"

    @property
    def emoji(self) -> str:
        return {
            Stage.STOPPED: "\N{MEDIUM BLACK CIRCLE}",
            Stage.PENDING: "\N{LARGE YELLOW CIRCLE}",
            Stage.BOOTING: "\N{LARGE ORANGE CIRCLE}",
            Stage.READY: "\N{LARGE GREEN CIRCLE}",
            Stage.STOPPING: "\N{LARGE ORANGE CIRCLE}",
            Stage.UNKNOWN: "\N{BLACK QUESTION MARK ORNAMENT}",
        }[self]


class OperationError(RuntimeError):
    """A command could not do what was asked. The message is shown to the user."""


@dataclass
class Snapshot:
    instance: Instance
    stage: Stage
    players: list[str]
    player_count: int
    rcon_error: str = ""

    @property
    def uptime(self) -> dt.timedelta | None:
        if not self.instance.launch_time or not self.instance.is_running:
            return None
        return dt.datetime.now(dt.UTC) - self.instance.launch_time


def _stage_for(instance: Instance, ready: bool) -> Stage:
    match instance.state:
        case "stopped":
            return Stage.STOPPED
        case "pending":
            return Stage.PENDING
        case "stopping" | "shutting-down":
            return Stage.STOPPING
        case "running":
            return Stage.READY if ready else Stage.BOOTING
        case _:
            return Stage.UNKNOWN


def _json_report(stdout: str, *, what: str) -> dict:
    """Every one of pzserver's newer tools answers in JSON. Insist on it.

    A tool that printed prose instead of JSON has almost certainly failed in a way its
    exit status did not capture, and treating that as an empty result would report "no
    mods" for a server whose .ini could not be read.
    """
    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        raise OperationError(
            f"Unreadable `{what}` response from the game server:"
            f"\n```\n{stdout[-800:] or '(nothing)'}\n```"
        ) from None


class GameServer:
    def __init__(self, aws: Aws, cfg: Config) -> None:
        self.aws = aws
        self.cfg = cfg
        self.rcon = Rcon(cfg.rcon_host, cfg.rcon_port, cfg.rcon_password)

    # --- Observation -----------------------------------------------------------------

    async def _describe_game(self) -> Instance:
        """Describe the game server, following it if the instance itself was replaced.

        `config.load` discovers the instance by tag and its docstring promises that "if
        the instance is ever rebuilt, the bot follows it without a redeploy". It did not:
        the id was resolved once at startup and pinned for the life of the process, so a
        `terraform apply` that replaced the instance left every command -- `/pz status`
        and `/pz start` included -- pointed at the corpse of the old one. Nothing
        detected it either: `systemctl is-active` said active and the `PZ/BotAlive`
        heartbeat kept ticking, because neither of those looks at the game server at all.

        `probe()` a few lines below already re-follows the private IP for exactly this
        reason. The instance id is the other half of the same rebuild.

        Re-resolution goes through the same `pz:stack` + `pz:role=gameserver` tag pair
        that `pz-bot-role` is scoped by, so this can never follow the bot onto a box its
        own credentials cannot touch.
        """
        # Annotated `Exception`, not `AwsError`: that name is a *tuple* of classes for
        # `except` to unpack, and using it as a type is the same confusion that once took
        # down the error handler itself (`case AwsError():` -- see bot.py).
        gone: Exception | None = None
        try:
            instance = await self.aws.describe(self.cfg.game_instance_id)
        except AwsError as exc:
            # Every other AWS failure is somebody else's problem to report. This one is
            # the recoverable one, and only this one.
            if not is_instance_gone(exc):
                raise
            gone = exc
        else:
            # A terminated instance still answers DescribeInstances for about an hour
            # after a rebuild, so "gone" has two shapes and this is the earlier one.
            if instance.state != "terminated":
                return instance

        replacement = await self.aws.find_instance(stack=self.cfg.stack, role="gameserver")
        if not replacement or replacement == self.cfg.game_instance_id:
            if gone is None:
                return instance  # terminated, and nothing has taken its place yet
            raise OperationError(
                f"The game server `{self.cfg.game_instance_id}` no longer exists, and "
                f"nothing is tagged `pz:stack={self.cfg.stack}` `pz:role=gameserver` in "
                f"{self.cfg.region} to take its place. Either the stack is mid-apply or "
                "it has not been applied \N{EM DASH} check `terraform plan` in pzserver."
            )

        log.warning(
            "game server was replaced: %s is gone, following the tag to %s",
            self.cfg.game_instance_id,
            replacement,
        )
        self.cfg.game_instance_id = replacement
        return await self.aws.describe(replacement)

    async def probe(self, *, rcon_timeout: float = 6.0) -> Snapshot:
        """Live state. Never cached, never inferred from a previous call."""
        instance = await self._describe_game()
        if not instance.is_running:
            return Snapshot(instance, _stage_for(instance, False), [], 0)

        # The private IP survives stop/start, but not a rebuild. Following it here means
        # a replaced instance does not need a bot restart.
        if instance.private_ip and instance.private_ip != self.rcon.host:
            log.info("game server private ip moved to %s", instance.private_ip)
            self.rcon.host = instance.private_ip

        try:
            out = await self.rcon.execute("players", timeout=rcon_timeout)
        except RconAuthError as exc:
            # Not a readiness problem: the server may be perfectly healthy and the bot's
            # copy of the password stale. Saying "still loading" here would hide it.
            return Snapshot(instance, Stage.UNKNOWN, [], 0, rcon_error=str(exc))
        except RconUnreachable as exc:
            return Snapshot(instance, Stage.BOOTING, [], 0, rcon_error=str(exc))

        if not rcon_mod.looks_ready(out):
            return Snapshot(
                instance,
                Stage.BOOTING,
                [],
                0,
                rcon_error="RCON answered but the response was not a player list",
            )
        return Snapshot(
            instance,
            Stage.READY,
            rcon_mod.parse_players(out),
            rcon_mod.parse_player_count(out),
        )

    # --- Lifecycle -------------------------------------------------------------------

    async def start(self, progress: Progress) -> Snapshot:
        """Stopped -> Pending -> Booting -> Ready, or clean up and raise.

        The failure path matters as much as the success path: a start that dies halfway
        leaves an m7i.xlarge running at $0.20/hour with no world on it, and nobody
        watching. Every exit from here either reaches Ready or stops the instance.
        """
        snap = await self.probe()
        if snap.stage is Stage.READY:
            return snap
        if snap.stage is Stage.STOPPING:
            raise OperationError(
                "The server is in the middle of shutting down. Wait for it to finish "
                "(about a minute) and start it again -- starting now would race the save."
            )
        if snap.stage in (Stage.PENDING, Stage.BOOTING):
            await progress("Already starting \N{EM DASH} following the one already in flight.")
        else:
            await progress("Starting the instance\N{HORIZONTAL ELLIPSIS}")
            await self.aws.start_instance(self.cfg.game_instance_id)

        started = asyncio.get_running_loop().time()

        def elapsed() -> int:
            return int(asyncio.get_running_loop().time() - started)

        # Phase 1: EC2 reports running.
        while True:
            snap = await self.probe()
            if snap.instance.is_running:
                break
            if elapsed() > self.cfg.start_running_timeout:
                await self._abort_start("the instance never reached `running`")
                raise OperationError(
                    f"The instance was still `{snap.instance.state}` after "
                    f"{self.cfg.start_running_timeout // 60} minutes. It has been stopped so "
                    "it cannot bill for nothing. This is an AWS-side problem \N{EM DASH} "
                    "try again."
                )
            await progress(f"Starting the instance\N{HORIZONTAL ELLIPSIS} ({elapsed()}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

        await progress(
            "Instance is up. Loading the world \N{EM DASH} this takes 2\N{EN DASH}5 minutes."
        )

        # Phase 2: RCON answers. This is the only definition of ready.
        while True:
            snap = await self.probe()
            if snap.stage is Stage.READY:
                return snap
            if snap.stage is Stage.UNKNOWN and snap.rcon_error:
                await self._abort_start("RCON rejected the bot's password")
                raise OperationError(
                    f"The world loaded but RCON refused the bot's password: "
                    f"{snap.rcon_error}\nThe instance has been stopped. Check "
                    f"`{self.cfg.ssm('rcon_password')}` against the server's .ini."
                )
            if elapsed() > self.cfg.start_ready_timeout:
                await self._abort_start("the world never finished loading")
                raise OperationError(
                    f"The instance came up but PZ never answered RCON within "
                    f"{self.cfg.start_ready_timeout // 60} minutes. It has been stopped. "
                    f"Check `journalctl -u pzserver` on {self.cfg.game_instance_id}."
                )
            mins, secs = divmod(elapsed(), 60)
            await progress(f"Loading the world\N{HORIZONTAL ELLIPSIS} ({mins}m {secs:02d}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

    async def _abort_start(self, why: str) -> None:
        log.error("aborting start: %s", why)
        try:
            await self.aws.stop_instance(self.cfg.game_instance_id)
        except Exception:  # noqa: BLE001 -- the caller is already raising; log and move on
            log.exception("could not stop the instance after a failed start")

    async def stop(self, progress: Progress, *, force: bool = False) -> None:
        """Warn, save, back up, stop.

        The save is not this function's responsibility to guarantee -- pzserver.service's
        ExecStop runs `pz-rcon save` on the way down no matter who initiated the stop
        (pzserver DESIGN G5), and the instance's shutdown behaviour is ACPI stop, so
        `ec2:StopInstances` reaches it. What this adds is the human part: telling players
        first, and taking a `prestop` archive to S3 while the world is still up.
        """
        snap = await self.probe()
        if snap.instance.is_stopped:
            raise OperationError("The server is already stopped.")
        if snap.stage is Stage.STOPPING:
            raise OperationError("The server is already shutting down.")

        grace = 0 if force or snap.player_count == 0 else self.cfg.stop_grace_seconds
        if grace:
            await progress(
                f"{snap.player_count} player(s) online \N{EM DASH} warning them and waiting "
                f"{grace}s before shutting down."
            )
            await self._broadcast(f"Server shutting down in {grace} seconds. Get somewhere safe.")
            # Warn again near the end; a message ninety seconds ago is not a warning.
            await asyncio.sleep(max(grace - 30, 0))
            await self._broadcast("Server shutting down in 30 seconds.")
            await asyncio.sleep(min(grace, 30))

        await progress("Saving and backing up\N{HORIZONTAL ELLIPSIS}")
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("backup"),
            {"mode": "prestop", "label": ""},
            timeout=900,
            comment="pzbot /pz stop",
        )
        if not result.ok:
            # Deliberately not fatal. The backup is the *second* line of defence; the
            # first is ExecStop, which runs regardless. Refusing to stop here would mean
            # a broken backup script keeps an expensive instance running indefinitely.
            log.error("pre-stop backup failed: %s", result.output[-2000:])
            await progress(
                "\N{WARNING SIGN} The pre-stop backup failed \N{EM DASH} stopping anyway. "
                "The world is still saved on the way down by `ExecStop`, but check the "
                "backup script."
            )

        await progress("Stopping the instance\N{HORIZONTAL ELLIPSIS}")
        await self.aws.stop_instance(self.cfg.game_instance_id)

        deadline = asyncio.get_running_loop().time() + 300
        while asyncio.get_running_loop().time() < deadline:
            await asyncio.sleep(self.cfg.poll_seconds)
            instance = await self.aws.describe(self.cfg.game_instance_id)
            if instance.is_stopped:
                return
            await progress(f"Stopping the instance\N{HORIZONTAL ELLIPSIS} (`{instance.state}`)")
        raise OperationError(
            "`ec2:StopInstances` was accepted but the instance is still not `stopped` "
            "after 5 minutes. It may still be saving a large world. Check `/pz status`; "
            "if it is still running in ten minutes, stop it from the console."
        )

    async def restart(self, progress: Progress) -> Snapshot:
        """Bounce PZ without stopping the instance.

        `systemctl restart` runs ExecStop, which saves and quits, so this inherits the
        same guarantee a full stop has.
        """
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError("The instance is not running \N{EM DASH} use `/pz start` instead.")

        if snap.player_count:
            await self._broadcast("Server restarting in 30 seconds. Get somewhere safe.")
            await progress(
                f"Warning {snap.player_count} player(s), restarting in 30s\N{HORIZONTAL ELLIPSIS}"
            )
            await asyncio.sleep(30)

        await progress("Restarting the server (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("lifecycle"),
            {"action": "restart"},
            timeout=300,
            comment="pzbot /pz restart",
        )
        if not result.ok:
            raise OperationError(f"`systemctl restart` failed:\n```\n{result.output[-1500:]}\n```")

        return await self._wait_until_ready(
            progress,
            timeout=self.cfg.start_ready_timeout,
            timeout_message=(
                "The server restarted but never answered RCON again. The instance has "
                "been left running deliberately so the logs survive \N{EM DASH} check "
                "`journalctl -u pzserver`, then `/pz stop` when you are done."
            ),
        )

    async def _wait_until_ready(
        self, progress: Progress, *, timeout: int, timeout_message: str
    ) -> Snapshot:
        """Poll until RCON answers, or give up with the caller's own explanation.

        Deliberately does not stop the instance on timeout: every caller of this is a
        server that was already running and is expected to still be running afterwards.
        `start()` has its own loop precisely because its failure path is the opposite --
        there, a box that never became ready must be stopped so it cannot bill.
        """
        started = asyncio.get_running_loop().time()
        while True:
            elapsed = int(asyncio.get_running_loop().time() - started)
            snap = await self.probe()
            if snap.stage is Stage.READY:
                return snap
            if elapsed > timeout:
                raise OperationError(timeout_message)
            mins, secs = divmod(elapsed, 60)
            await progress(f"Loading the world\N{HORIZONTAL ELLIPSIS} ({mins}m {secs:02d}s)")
            await asyncio.sleep(self.cfg.poll_seconds)

    # --- RCON-level operations -------------------------------------------------------

    async def save(self) -> str:
        snap = await self.probe()
        if snap.stage is not Stage.READY:
            raise OperationError(
                f"The server is `{snap.stage}` \N{EM DASH} there is nothing to save yet."
            )
        return await self.rcon.execute("save", timeout=30)

    async def _broadcast(self, message: str) -> None:
        # Quoted, because PZ's servermsg takes a single quoted argument. Callers pass
        # literals; nothing here is user-supplied.
        try:
            await self.rcon.execute(f'servermsg "{message}"')
        except rcon_mod.RconError as exc:
            log.warning("could not broadcast %r: %s", message, exc)

    # --- Backups ---------------------------------------------------------------------

    async def backup_now(self, label: str = "") -> CommandResult:
        if label and not LABEL.fullmatch(label):
            raise OperationError(
                "A backup label may only contain letters, numbers, `-` and `_` "
                "(40 characters max). It ends up in a filename and an S3 key."
            )
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                "The instance is stopped \N{EM DASH} there is nothing to back up live."
            )

        return await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("backup"),
            {"mode": "manual", "label": label},
            timeout=1800,
            comment="pzbot /pz backup now",
        )

    async def download_url(
        self, backup_name: str = "", *, minutes: int = DOWNLOAD_TTL_DEFAULT
    ) -> tuple[Backup, str, int]:
        """A time-limited link to one archive, or to the newest one when no name is given.

        Returns the backup, the URL, and the number of seconds it was signed for.

        This deliberately never touches the game server. The instance is stopped by
        default and the archive is in S3 either way, so "give me the world save" must not
        be a question that costs $0.20/hour to answer -- and the most likely moment to
        want a copy is precisely when the server is off, or broken, or mid-argument about
        whether to roll back.

        The name is re-checked against the live listing before anything is signed, the
        same rule `restore` follows. An autocomplete value can always be typed by hand,
        and S3 will happily sign a URL for a key that does not exist: the admin would get
        an XML `NoSuchKey` in a browser instead of a sentence explaining the typo.
        """
        minutes = max(DOWNLOAD_TTL_MIN, min(minutes, DOWNLOAD_TTL_MAX))

        backups = await self.aws.list_backups(self.cfg.backup_bucket, self.cfg.stack)
        if not backups:
            raise OperationError(
                f"There is nothing in `s3://{self.cfg.backup_bucket}/backups/"
                f"{self.cfg.stack}/`. That is worth investigating on its own \N{EM DASH} "
                "`pz-backup.sh` should be uploading every 30 minutes while the server runs."
            )

        if backup_name:
            if not BACKUP_NAME.fullmatch(backup_name):
                raise OperationError(
                    f"`{backup_name}` is not a backup name produced by this stack."
                )
            found = next((b for b in backups if b.name == backup_name), None)
            if found is None:
                raise OperationError(
                    f"No backup named `{backup_name}` in "
                    f"`s3://{self.cfg.backup_bucket}/backups/{self.cfg.stack}/`. "
                    "Use `/pz backup list` to see what exists."
                )
        else:
            found = backups[0]  # list_backups sorts newest first

        url = await self.aws.presign_backup(
            self.cfg.backup_bucket,
            found.key,
            expires_in=minutes * 60,
            filename=found.name,
        )
        # The name, never the URL. This line goes to journald and, via audit.py, to a
        # channel -- and the URL in either place would be the download link leaking into
        # a log with a longer retention than the link's own lifetime.
        log.info("signed a %d-minute download link for %s", minutes, found.name)
        return found, url, minutes * 60

    async def restore(self, backup_name: str, progress: Progress) -> CommandResult:
        """Stop PZ, restore, bring it back. The most dangerous thing the bot can do.

        `pz-restore.sh` carries the real guards -- it refuses to run under a live server,
        takes a `prerestore` backup first, and refuses a partial archive. What is added
        here is that the name is checked against the actual S3 listing before it goes
        anywhere near a shell.
        """
        if not BACKUP_NAME.fullmatch(backup_name):
            raise OperationError(f"`{backup_name}` is not a backup name produced by this stack.")

        backups = await self.aws.list_backups(self.cfg.backup_bucket, self.cfg.stack)
        if backup_name not in {b.name for b in backups}:
            raise OperationError(
                f"No backup named `{backup_name}` in "
                f"`s3://{self.cfg.backup_bucket}/backups/{self.cfg.stack}/`. "
                "Use `/pz backup list` to see what exists."
            )

        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                "The instance must be running to restore. `/pz start` first \N{EM DASH} the "
                "restore stops the game itself, but it needs the box up to do the work."
            )
        if snap.player_count:
            raise OperationError(
                f"{snap.player_count} player(s) are online. Restoring would delete the "
                "session they are in. Get everyone off first."
            )

        await progress("Stopping the game (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
        stop = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("lifecycle"),
            {"action": "stop"},
            timeout=300,
            comment="pzbot /pz restore (stop)",
        )
        if not stop.ok:
            raise OperationError(
                "Could not stop the game, so nothing was restored:\n"
                f"```\n{stop.output[-1200:]}\n```"
            )

        await progress(
            "Taking a prerestore backup and restoring\N{HORIZONTAL ELLIPSIS} "
            "(this can take a while)"
        )
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("restore"),
            {"backupName": backup_name},
            timeout=3600,
            comment="pzbot /pz restore",
        )
        if not result.ok:
            raise OperationError(
                "The restore failed. `pz-restore.sh` fails closed \N{EM DASH} your world has "
                "not been touched, and the prerestore backup it took is intact. The game is "
                "still stopped; `/pz restart` brings it back on the old world.\n"
                f"```\n{result.output[-1200:]}\n```"
            )

        await progress("Restored. Starting the game back up\N{HORIZONTAL ELLIPSIS}")
        start = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("lifecycle"),
            {"action": "start"},
            timeout=300,
            comment="pzbot /pz restore (start)",
        )
        if not start.ok:
            raise OperationError(
                "The restore succeeded but the server did not come back up:\n"
                f"```\n{start.output[-1200:]}\n```"
            )
        return result

    # --- Reaching the game server over SSM --------------------------------------------

    async def _require_instance_running(self, what: str) -> Snapshot:
        """SSM only reaches a running instance, and "InvalidInstanceId" explains nothing.

        Every path that sends a command to the game server goes through here, so the
        answer to "why did /pz config get just throw an AWS error" is a sentence about
        the server being off instead.
        """
        snap = await self.probe()
        if not snap.instance.is_running:
            raise OperationError(
                f"The instance is stopped, so {what} is not reachable \N{EM DASH} the data "
                "volume it lives on is only attached while the box is up. `/pz start` first."
            )
        return snap

    async def _lifecycle(self, action: str, *, comment: str) -> CommandResult:
        return await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("lifecycle"),
            {"action": action},
            timeout=300,
            comment=comment,
        )

    # --- Editing a file the running game owns -----------------------------------------
    #
    # Three operations -- a sandbox option, the mod list, a Steam build -- all need the
    # same sequence, and it is a sequence with a sharp edge in the middle: between the
    # stop and the start there is an instance that is running, billing, and has no game
    # on it. Every failure path below therefore ends with the server back up rather than
    # with an exception thrown over a stopped world.

    async def _stop_for_edit(
        self, snap: Snapshot, progress: Progress, *, why: str, comment: str, on_fail: str
    ) -> None:
        """Warn whoever is playing, then stop the game so its files can be edited."""
        if snap.player_count:
            await self._broadcast(f"Server restarting in 30 seconds {why}.")
            await progress(
                f"Warning {snap.player_count} player(s), restarting in 30s\N{HORIZONTAL ELLIPSIS}"
            )
            await asyncio.sleep(30)

        await progress("Stopping the game (it saves on the way down)\N{HORIZONTAL ELLIPSIS}")
        stop = await self._lifecycle("stop", comment=comment)
        if not stop.ok:
            raise OperationError(f"{on_fail}\n```\n{stop.output[-1000:]}\n```")

    async def _start_after_edit(
        self,
        progress: Progress,
        *,
        line: str,
        comment: str,
        on_fail: str,
        on_timeout: str,
    ) -> Snapshot:
        await progress(line)
        start = await self._lifecycle("start", comment=comment)
        if not start.ok:
            raise OperationError(f"{on_fail}\n```\n{start.output[-1000:]}\n```")
        return await self._wait_until_ready(
            progress, timeout=self.cfg.start_ready_timeout, timeout_message=on_timeout
        )

    async def _recover_from_failed_edit(self, progress: Progress, *, comment: str) -> None:
        """Put the game back up after an edit failed with it already stopped.

        Best-effort and deliberately not checked: the caller is about to raise the real
        error, and the state to avoid is an instance running with no server on it --
        billing at $0.20/hour with nobody able to play and nothing to say why.
        """
        await progress(
            "The edit failed. Starting the server back up unchanged\N{HORIZONTAL ELLIPSIS}"
        )
        await self._lifecycle("start", comment=comment)

    async def _backup_before(self, label: str, progress: Progress) -> None:
        """Take a labelled backup before a change that can make the world unloadable.

        Unlike `stop()`, which stops anyway when its backup fails, this one REFUSES. The
        difference is what the backup is for: there, it is a bonus on top of the save
        `ExecStop` performs regardless; here, it is the entire reason a bad mod or a
        B41-to-B42 branch switch is survivable. pzserver DESIGN section 13 names this
        pre-change backup as the prerequisite for managing mods from chat at all.
        """
        await progress(f"Taking a `{label}` backup first\N{HORIZONTAL ELLIPSIS}")
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("backup"),
            {"mode": "manual", "label": label},
            timeout=1800,
            comment=f"pzbot {label}",
        )
        if not result.ok:
            raise OperationError(
                "The pre-change backup failed, so nothing was changed. This change is "
                "one of the few that can leave a world that will not load, and it is not "
                "worth making without a way back.\n"
                f"```\n{result.output[-1000:]}\n```"
            )

    # --- Sandbox options (the world's rules) -----------------------------------------

    @property
    def sandbox_path(self) -> str:
        return f"/opt/pz/data/Zomboid/Server/{self.cfg.server_name}_SandboxVars.lua"

    async def sandbox_read(self) -> dict[str, str]:
        """Every sandbox value the world currently has, as raw Lua literals."""
        await self._require_instance_running("the world's settings file")
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("sandbox"),
            {"action": "get", "path": self.sandbox_path},
            timeout=60,
            comment="pzbot /pz sandbox get",
        )
        if not result.ok:
            raise OperationError(
                f"Could not read the sandbox options:\n```\n{result.output[-800:]}\n```"
            )
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise OperationError(f"Unreadable response from the game server: {exc}") from None

    async def sandbox_set(
        self, path: str, value: str, progress: Progress, *, apply: bool = True
    ) -> dict[str, str]:
        """Change one sandbox option.

        Unlike the .ini, this file is only read when the server starts, so there is no
        `reloadoptions` equivalent -- the change lands on the next boot or not at all.
        Worse, a running server owns the file: an admin changing an option from inside
        the game rewrites it wholesale, which would silently undo an edit made
        underneath. So when `apply` is set and the game is up, the order is
        **stop, edit, start** rather than edit-then-restart. There is no window in which
        both this bot and the game think they own the file.
        """
        try:
            literal = sandbox.coerce(path, value)
        except sandbox.SandboxError as exc:
            raise OperationError(str(exc)) from None

        snap = await self._require_instance_running("the world's settings file")

        game_was_up = snap.stage in (Stage.READY, Stage.BOOTING)
        if apply and game_was_up:
            await self._stop_for_edit(
                snap,
                progress,
                why="to change the world settings",
                comment="pzbot /pz sandbox set (stop)",
                on_fail="Could not stop the game, so nothing was changed:",
            )

        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("sandbox"),
            {"action": "set", "path": self.sandbox_path, "key": path, "value": literal},
            timeout=60,
            comment="pzbot /pz sandbox set",
        )
        if not result.ok:
            if apply and game_was_up:
                await self._recover_from_failed_edit(
                    progress, comment="pzbot /pz sandbox set (recover)"
                )
            raise OperationError(
                f"Could not change the sandbox options:\n```\n{result.output[-800:]}\n```"
            )

        try:
            changed = json.loads(result.stdout)
        except json.JSONDecodeError:
            changed = {"setting": path, "was": "?", "now": literal}

        if apply and game_was_up:
            await self._start_after_edit(
                progress,
                line="Starting back up on the new settings\N{HORIZONTAL ELLIPSIS}",
                comment="pzbot /pz sandbox set (start)",
                on_fail=(
                    "The setting was changed, but the server did not come back up. The "
                    "previous file is on the box as `*_SandboxVars.lua.pzbot.bak`."
                ),
                on_timeout=(
                    "The setting was changed and the server was restarted, but it never "
                    "answered RCON again. The instance has been left running so the logs "
                    "survive -- check `journalctl -u pzserver`. The previous file is on "
                    "the box as `*_SandboxVars.lua.pzbot.bak`."
                ),
            )

        changed["applied"] = "yes" if (apply and game_was_up) else "next start"
        return changed

    # --- The .ini allowlist ----------------------------------------------------------

    @property
    def ini_path(self) -> str:
        return f"/opt/pz/data/Zomboid/Server/{self.cfg.server_name}.ini"

    async def ini_read(self) -> dict[str, str]:
        await self._require_instance_running("the server's .ini")
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("config-read"),
            {},
            timeout=60,
            comment="pzbot /pz config get",
        )
        if not result.ok:
            raise OperationError(f"Could not read the .ini:\n```\n{result.output[-800:]}\n```")
        values: dict[str, str] = {}
        for line in result.stdout.splitlines():
            if "=" in line:
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
        return values

    async def ini_write(self, key: str, value: str) -> str:
        """Set one allowlisted key, then make PZ re-read the file.

        The allowlist is the whole security model here. `/pz config` must not become a
        way to edit an arbitrary line of an arbitrary file on the game server from a chat
        message -- so the key is looked up in a table (never interpolated from input),
        and the value is validated by that table's own rule before it goes anywhere.
        """
        spec = INI_KEYS.get(key)
        if spec is None:
            raise OperationError(f"`{key}` is not an editable key. See `/pz config get`.")
        value = spec.clean(value)

        snap = await self._require_instance_running("the server's .ini")

        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("config-write"),
            {"key": key, "value": value},
            timeout=60,
            comment="pzbot /pz config set",
        )
        if not result.ok:
            raise OperationError(f"Could not write the .ini:\n```\n{result.output[-800:]}\n```")

        if snap.stage is Stage.READY:
            try:
                await self.rcon.execute("reloadoptions", timeout=30)
            except rcon_mod.RconError as exc:
                return (
                    f"`{key}` is now `{value}` in the .ini, but `reloadoptions` failed "
                    f"({exc}). It will take effect on the next restart."
                )
            return f"`{key}` is now `{value}`, and the server has reloaded its options."
        return f"`{key}` is now `{value}`. It takes effect on the next start."

    # --- Idle shutdown ---------------------------------------------------------------

    async def set_idle(self, timeout_min: int, warn_min: int) -> str:
        """Retune the watchdog for the current session.

        This edits `/etc/pz/env` on the game server rather than Parameter Store, and that
        is not a shortcut -- it is the only door the bot has. `pz-bot-role` deliberately
        has no `ssm:PutParameter` (pzserver DESIGN section 9), and `pz-config.service`
        re-renders that file from Parameter Store on every boot, so a change made here
        lasts exactly as long as the session it was made in. Making it permanent means
        `prod.tfvars` and an apply, which is a decision worth taking outside of chat.
        """
        if not 5 <= timeout_min <= 1440:
            raise OperationError("The idle timeout must be between 5 and 1440 minutes.")
        warn_min = max(1, min(warn_min, timeout_min - 1))

        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("idle-retune"),
            {"timeoutMin": str(timeout_min), "warnMin": str(warn_min)},
            timeout=60,
            comment="pzbot /pz idle",
        )
        if not result.ok:
            raise OperationError(
                f"Could not retune the watchdog:\n```\n{result.output[-800:]}\n```"
            )
        return result.stdout.strip()

    # --- The game build, and the mods on top of it -------------------------------------
    #
    # Two capabilities that pzserver DESIGN section 13 deferred out of v1 together, and
    # for the same reason: both change what code the world loads, and getting either
    # wrong produces a save that will not open rather than a server that will not start.
    # Everything here therefore routes through `_backup_before`, which refuses the change
    # if the backup fails.

    async def _version_command(
        self, action: str, branch: str = "", *, timeout: int = 120
    ) -> dict[str, str]:
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("version"),
            {"action": action, "branch": branch},
            timeout=timeout,
            comment=f"pzbot /pz version {action}",
        )
        if not result.ok:
            raise OperationError(
                f"`{action}` failed on the game server:\n```\n{result.output[-1000:]}\n```"
            )
        return _json_report(result.stdout, what="version")

    async def version_status(self) -> dict[str, str]:
        await self._require_instance_running("the game install")
        return await self._version_command("status")

    async def version_hold(self, on: bool) -> dict[str, str]:
        """Pin the build on disk, or resume updating.

        Not gated on the game being stopped: this writes a flag that `pz-update.sh` reads
        at the START of the next session, so setting it mid-session changes nothing about
        the session it is set in, which is the point of it.
        """
        await self._require_instance_running("the version pin")
        return await self._version_command("hold" if on else "unhold")

    async def version_update(
        self, progress: Progress, *, validate: bool = False, branch: str = ""
    ) -> dict[str, str]:
        """Move this box to another build: latest on its branch, another branch, or repair.

        The order is **back up, stop, update, start**, and the stop is not optional when
        the game is up: SteamCMD rewriting files underneath a running JVM is its own kind
        of corruption, and PZ will not notice until it crashes an hour later.
        """
        if branch and not STEAM_BRANCH.fullmatch(branch):
            raise OperationError(
                f"`{branch}` is not a Steam branch name \N{EM DASH} letters, numbers, "
                "`.`, `-` and `_`, up to 32 characters."
            )

        snap = await self._require_instance_running("the game install")
        game_was_up = snap.stage in (Stage.READY, Stage.BOOTING)

        if branch:
            label = "before-branch-switch"
        elif validate:
            label = "before-validate"
        else:
            label = "before-update"
        await self._backup_before(label, progress)

        if game_was_up:
            await self._stop_for_edit(
                snap,
                progress,
                why="to update the game",
                comment="pzbot /pz version update (stop)",
                on_fail="Could not stop the game, so nothing was updated:",
            )

        try:
            if branch:
                await progress(f"Pinning the Steam branch to `{branch}`\N{HORIZONTAL ELLIPSIS}")
                await self._version_command("branch", branch)
            if validate:
                await progress(
                    "Re-checksumming every file against Steam\N{HORIZONTAL ELLIPSIS} "
                    "(this takes a while)"
                )
            else:
                await progress("Running SteamCMD\N{HORIZONTAL ELLIPSIS}")
            status = await self._version_command("validate" if validate else "update", timeout=3600)
        except OperationError:
            if game_was_up:
                await self._recover_from_failed_edit(
                    progress, comment="pzbot /pz version update (recover)"
                )
            raise

        if game_was_up:
            await self._start_after_edit(
                progress,
                line="Starting back up on the new build\N{HORIZONTAL ELLIPSIS}",
                comment="pzbot /pz version update (start)",
                on_fail=(
                    "The update ran, but the server did not come back up. If the build it "
                    "landed on is the problem, `/pz version hold` and a `/pz restore` of "
                    f"the `{label}` backup put you back where you were."
                ),
                on_timeout=(
                    "The update ran and the server was restarted, but it never answered "
                    "RCON again. The instance has been left running so the logs survive "
                    "\N{EM DASH} check `journalctl -u pzserver`. The world as it was before "
                    f"this is in the `{label}` backup."
                ),
            )

        status["applied"] = "yes" if game_was_up else "next start"
        status["backup_label"] = label
        return status

    # --- Mods --------------------------------------------------------------------------

    async def _mods_command(self, action: str, workshop_id: str = "", mod_ids: str = "") -> dict:
        result = await self.aws.send_command(
            self.cfg.game_instance_id,
            self.cfg.document("mods"),
            {"action": action, "workshopId": workshop_id, "modIds": mod_ids},
            timeout=120,
            comment=f"pzbot /pz mods {action}",
        )
        if not result.ok:
            raise OperationError(
                f"`mods {action}` failed on the game server:\n```\n{result.output[-1000:]}\n```"
            )
        return _json_report(result.stdout, what="mods")

    async def mods_list(self) -> dict:
        await self._require_instance_running("the server's mod list")
        return await self._mods_command("list")

    async def mods_check(self) -> str:
        """Ask the running server whether its Workshop mods have updates waiting.

        PZ answers this one into its own log rather than over RCON -- the RCON reply is an
        acknowledgement, not a result -- so this reports what the server said and leaves
        the interpretation to whoever asked. Worth having anyway: a mod update is picked
        up by restarting, and knowing there is one to pick up is the whole question.
        """
        snap = await self.probe()
        if snap.stage is not Stage.READY:
            raise OperationError(
                f"The server is `{snap.stage}` \N{EM DASH} only a running server can check "
                "its mods."
            )
        return await self.rcon.execute("checkModsNeedUpdate", timeout=30)

    async def mods_add(
        self, workshop_id: str, mod_ids: str, progress: Progress, *, apply: bool = True
    ) -> dict:
        workshop_id = workshop_id.strip()
        if not WORKSHOP_ID.fullmatch(workshop_id):
            raise OperationError(
                f"`{workshop_id}` is not a Steam Workshop id. It is the number at the end "
                "of the item's Workshop URL \N{EM DASH} `?id=2169435993`."
            )

        wanted = [item for item in re.split(r"[,;\s]+", mod_ids) if item]
        for mod_id in wanted:
            if not MOD_ID.fullmatch(mod_id):
                raise OperationError(
                    f"`{mod_id}` is not a mod id. Mod ids are the names on the Workshop "
                    "page under \N{LEFT DOUBLE QUOTATION MARK}Mod ID"
                    "\N{RIGHT DOUBLE QUOTATION MARK}, not the item's title."
                )
        joined = ",".join(wanted)
        if len(joined) > 400:
            raise OperationError(
                "That is more mod ids than one Workshop item plausibly ships (400 "
                "characters max). Add it in two goes if it really does."
            )

        return await self._change_mods(
            "add", progress, apply=apply, workshop_id=workshop_id, mod_ids=joined
        )

    async def mods_remove(
        self, workshop_id: str, progress: Progress, *, apply: bool = True
    ) -> dict:
        workshop_id = workshop_id.strip()
        if not WORKSHOP_ID.fullmatch(workshop_id):
            raise OperationError(f"`{workshop_id}` is not a Steam Workshop id.")
        return await self._change_mods("remove", progress, apply=apply, workshop_id=workshop_id)

    async def mods_scan(self, progress: Progress) -> dict:
        """Attribute the Workshop items the server has downloaded since they were added.

        Adding an item the server has not downloaded yet can only write `WorkshopItems=`,
        because the mod ids that belong in `Mods=` are inside the item. This is the second
        half of that: it reads the downloaded items and fills `Mods=` in. `mods_add` runs
        it for you when it has to; this is the door for the times it could not.
        """
        await self._require_instance_running("the server's mod list")
        await progress("Reading the downloaded Workshop items\N{HORIZONTAL ELLIPSIS}")
        return await self._mods_command("scan")

    async def _change_mods(
        self,
        action: str,
        progress: Progress,
        *,
        apply: bool,
        workshop_id: str = "",
        mod_ids: str = "",
    ) -> dict:
        """Back up, stop, edit the mod list, start. Optionally twice -- see below."""
        snap = await self._require_instance_running("the server's mod list")
        game_was_up = snap.stage in (Stage.READY, Stage.BOOTING)
        restart = apply and game_was_up

        await self._backup_before("before-mods", progress)

        if restart:
            await self._stop_for_edit(
                snap,
                progress,
                why="to change the mod list",
                comment=f"pzbot /pz mods {action} (stop)",
                on_fail="Could not stop the game, so the mod list was not changed:",
            )

        try:
            report = await self._mods_command(action, workshop_id, mod_ids)
        except OperationError:
            if restart:
                await self._recover_from_failed_edit(
                    progress, comment=f"pzbot /pz mods {action} (recover)"
                )
            raise

        if not restart:
            report["applied"] = "next start"
            return report

        await self._start_after_edit(
            progress,
            line="Starting back up with the new mod list\N{HORIZONTAL ELLIPSIS}",
            comment=f"pzbot /pz mods {action} (start)",
            on_fail=(
                "The mod list was changed, but the server did not come back up. A mod "
                "that will not load is the usual cause; the previous `.ini` is on the box "
                "as `*.ini.pzbot.bak` and the `before-mods` backup is in S3."
            ),
            on_timeout=(
                "The mod list was changed and the server was restarted, but it never "
                "answered RCON again \N{EM DASH} which is what a mod that fails to load "
                "looks like. Check `journalctl -u pzserver`; the previous `.ini` is on the "
                "box as `*.ini.pzbot.bak`."
            ),
        )
        report["applied"] = "yes"

        # The second restart, and the reason this method is not just stop-edit-start.
        #
        # An item added without its mod ids could only be written to `WorkshopItems=`,
        # because the ids live inside an item that was not on disk yet. The start above is
        # what downloaded it -- so the ids are now readable, but PZ read `Mods=` before
        # they were written into it. Without this the mod is listed, downloaded, and does
        # nothing, which is the single most confusing state in PZ mod management.
        if report.get("pending"):
            await progress("Downloaded. Working out which mods it ships\N{HORIZONTAL ELLIPSIS}")
            scan = await self._mods_command("scan")
            report["scanned"] = scan
            if scan.get("resolved"):
                await self._stop_for_edit(
                    await self.probe(),
                    progress,
                    why="to load the mods that just downloaded",
                    comment=f"pzbot /pz mods {action} (stop for scan)",
                    on_fail=(
                        "The mods were found, but the server could not be stopped to load "
                        "them. They take effect on the next restart:"
                    ),
                )
                await self._start_after_edit(
                    progress,
                    line="Starting again, this time with the mods loaded\N{HORIZONTAL ELLIPSIS}",
                    comment=f"pzbot /pz mods {action} (start for scan)",
                    on_fail="The mods were found, but the server did not come back up.",
                    on_timeout=(
                        "The mods were found and the server was restarted, but it never "
                        "answered RCON again \N{EM DASH} check `journalctl -u pzserver`."
                    ),
                )
                report["applied"] = "yes, after two restarts"

        return report


@dataclass(frozen=True)
class IniKey:
    """One editable server option, and the rule that keeps it editable-but-safe."""

    kind: str  # int | bool | text
    help: str
    low: int = 0
    high: int = 0
    max_len: int = 200

    def clean(self, value: str) -> str:
        value = value.strip()
        if self.kind == "int":
            try:
                number = int(value)
            except ValueError:
                raise OperationError(f"`{value}` is not a number.") from None
            if not self.low <= number <= self.high:
                raise OperationError(f"Must be between {self.low} and {self.high}.")
            return str(number)
        if self.kind == "bool":
            if value.lower() in ("true", "yes", "on", "1"):
                return "true"
            if value.lower() in ("false", "no", "off", "0"):
                return "false"
            raise OperationError(f"`{value}` is not true or false.")
        # Text. Newlines would inject a second .ini line, and `=` would split the key.
        if len(value) > self.max_len:
            raise OperationError(f"Too long — {self.max_len} characters max.")
        if re.search(r"[\x00-\x1f]", value) or "=" in value:
            raise OperationError(
                "No control characters and no `=` \N{EM DASH} both corrupt the .ini."
            )
        return value


# Deliberately short. Every entry here is something a group actually changes mid-season;
# anything structural (ports, passwords, the world name) belongs in Terraform, where it
# is reviewed, and not in a chat message.
INI_KEYS: dict[str, IniKey] = {
    "PublicName": IniKey("text", "Name shown in the server browser", max_len=64),
    "PublicDescription": IniKey("text", "Description shown in the server browser"),
    "ServerWelcomeMessage": IniKey("text", "Message shown to a player on connect", max_len=300),
    "MaxPlayers": IniKey("int", "Player slots", low=1, high=64),
    "PauseEmpty": IniKey("bool", "Pause the world when nobody is online"),
    "GlobalChat": IniKey("bool", "Server-wide chat channel"),
    "PVP": IniKey("bool", "Player versus player damage"),
    "SafetySystem": IniKey("bool", "PVP safety toggle system"),
    "SleepAllowed": IniKey("bool", "Let players sleep"),
    "DisplayUserName": IniKey("bool", "Show usernames above characters"),
    "NoFire": IniKey("bool", "Disable fire spread"),
    "AnnounceDeath": IniKey("bool", "Announce deaths in chat"),
}
